version: "3"

services:
  api:
    container_name: api
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - redis
    ports:
      - 3000:3000
      - 9229:9229
    build: .

  redis:
    container_name: redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis:/usr/local/etc/redis/data
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis
    ports:
      - 6379:6379
    expose:
      - 6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - redis
    ports:
      - 8081:8081

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      PG_MODE: primary
      PG_PRIMARY_USER: postgres
      PG_PRIMARY_PASSWORD: admin
      PG_DATABASE: postgres
      PG_USER: postgres
      PG_PASSWORD: admin
      PG_ROOT_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@peak.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    logging:
      driver: none
    restart: unless-stopped

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            password: admin

volumes:
  redis:
  pgdata:
  pgadmin:

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
