version: "3"

services:
  api:
    container_name: api
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
      - 9229:9229
    build: .

  redis:
    container_name: redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    expose:
      - 6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      PG_MODE: primary
      PG_PRIMARY_USER: postgres
      PG_PRIMARY_PASSWORD: admin
      PG_DATABASE: db
      PG_USER: zach
      PG_PASSWORD: admin
      PG_ROOT_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: zach@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge
