version: "3"

services:
  api:
    container_name: api
    env_file: .env
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    build: .

  redis:
    container_name: redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      # - /data/postgres:/data/postgres
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "/data/postgres:/var/lib/postgresql/data"
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
  
  postgres-data:
    container_name: postgres-data
    image: busybox
    volumes:
      - /var/lib/postgresql/data

volumes:
  mydata:
  postgres-data:

networks:
  postgres:
    driver: bridge
